### ISSUE TITLE
Fails to start past version 1.4.4

### ISSUE THREAD

**Issue by igbjnI05bF** [docusealco/docuseal#233]
Running on Debian 12, all versions past 1.4.4 fail to start, from what I can tell because of a ruby error. 

*****************************************************************************************************************
```
app_1       | WARNING: Nokogiri was built against libxml version 2.11.6, but has dynamically loaded 2.11.7
app_1       | => Booting Puma
app_1       | => Rails 7.1.2 application starting in production
app_1       | => Run `bin/rails server --help` for more startup options
app_1       | Exiting
app_1       | /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `delete': Resource busy @ apply2files - /dev/null (Errno::EBUSY)
app_1       | 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `check_pid!'
app_1       | 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:307:in `start'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:38:in `start'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
app_1       | 	from <internal:kernel>:90:in `tap'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
app_1       | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
app_1       | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
app_1       | 	from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
app_1       | 	from /app/bin/rails:4:in `<main>'
app_1       | WARNING: Nokogiri was built against libxml version 2.11.6, but has dynamically loaded 2.11.7
app_1       | => Booting Puma
app_1       | => Rails 7.1.2 application starting in production
app_1       | => Run `bin/rails server --help` for more startup options
app_1       | Exiting
app_1       | /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `delete': Resource busy @ apply2files - /dev/null (Errno::EBUSY)
app_1       | 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `check_pid!'
app_1       | 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:307:in `start'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:38:in `start'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
app_1       | 	from <internal:kernel>:90:in `tap'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
app_1       | 	from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
app_1       | 	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
app_1       | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
app_1       | 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
app_1       | 	from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
app_1       | 	from /app/bin/rails:4:in `<main>'
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2024-03-13 00:16:12.030 UTC [1] LOG:  starting PostgreSQL 15.6 (Debian 15.6-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_1  | 2024-03-13 00:16:12.030 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2024-03-13 00:16:12.030 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2024-03-13 00:16:12.031 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2024-03-13 00:16:12.036 UTC [29] LOG:  database system was shut down at 2024-03-13 00:16:08 UTC
postgres_1  | 2024-03-13 00:16:12.046 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2024-03-13 00:18:45.676 UTC [1] LOG:  received fast shutdown request
postgres_1  | 2024-03-13 00:18:45.681 UTC [1] LOG:  aborting any active transactions
postgres_1  | 2024-03-13 00:18:45.686 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
postgres_1  | 2024-03-13 00:18:45.686 UTC [27] LOG:  shutting down
postgres_1  | 2024-03-13 00:18:45.687 UTC [27] LOG:  checkpoint starting: shutdown immediate
postgres_1  | 2024-03-13 00:18:45.693 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.007 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
postgres_1  | 2024-03-13 00:18:45.697 UTC [1] LOG:  database system is shut down
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2024-03-13 00:19:12.561 UTC [1] LOG:  starting PostgreSQL 15.6 (Debian 15.6-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_1  | 2024-03-13 00:19:12.562 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2024-03-13 00:19:12.562 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2024-03-13 00:19:12.563 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2024-03-13 00:19:12.566 UTC [29] LOG:  database system was shut down at 2024-03-13 00:18:45 UTC
postgres_1  | 2024-03-13 00:19:12.573 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2024-03-13 00:20:33.182 UTC [1] LOG:  received fast shutdown request
postgres_1  | 2024-03-13 00:20:33.183 UTC [1] LOG:  aborting any active transactions
postgres_1  | 2024-03-13 00:20:33.185 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
postgres_1  | 2024-03-13 00:20:33.185 UTC [27] LOG:  shutting down
postgres_1  | 2024-03-13 00:20:33.186 UTC [27] LOG:  checkpoint starting: shutdown immediate
postgres_1  | 2024-03-13 00:20:33.192 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.007 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
postgres_1  | 2024-03-13 00:20:33.197 UTC [1] LOG:  database system is shut down
```
**************************************************************************************************
myusername@docuseal:~/docuseal$ sudo docker-compose ps
```
       Name                      Command              State    Ports
--------------------------------------------------------------------
docuseal_app_1        /app/bin/rails server           Exit 1
docuseal_postgres_1   docker-entrypoint.sh postgres   Exit 0
```
**************************************************************************************************

Versions 1.4.4 and below work fine. The *only* thing I edited in the docker-compose.yml is I deleted all lines referencing caddy because I already have caddy running in a separate container for all of my other reverse proxy needs.

**Comment by omohokcoj** [comment]
@igbjnI05bF /dev/null is not available on LXC - need to add PIDFILE variable and point it to the /tmp folder
https://github.com/docusealco/docuseal/issues/224#issuecomment-1974801465
