### ISSUE TITLE
trying to run docuseal on docker on unraid

### ISSUE THREAD

**Issue by schtack** [docusealco/docuseal#242]
Hi, 

I'm trying to run docuseal on docker on my nas using unraid with no luck.
if somebody have a tips or idea to help me this will be awesome !

below my log:

```
WARNING: Nokogiri was built against libxml version 2.11.6, but has dynamically loaded 2.11.7
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_many_inversing=' for ActiveRecord::Base:Class (NoMethodError)
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/railtie.rb:292:in `block (3 levels) in <class:Railtie>'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/railtie.rb:282:in `each'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/railtie.rb:282:in `block (2 levels) in <class:Railtie>'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:77:in `each'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/base.rb:15:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:506:in `migration_class'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:510:in `migration_connection'
        from /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
        from /app/config/initializers/migrate.rb:4:in `block in <main>'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:448:in `instance_exec'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:448:in `block in make_lambda'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:706:in `catch'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:203:in `block in halting'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `each'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `invoke_before'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
        from /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/reloader.rb:96:in `prepare!'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/application.rb:423:in `initialize!'
        from /app/config/environment.rb:7:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:312:in `block in start'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:311:in `start'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:38:in `start'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
=> Booting Puma
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
=> Rails 7.1.2 application starting in production 
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
        from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
=> Run `bin/rails server --help` for more startup options       from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in <main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /app/bin/rails:4:in `<main>'

Exiting
``` 
Thanks.

**Comment by AmbitionLover** [comment]
I have the same problem as you

**Comment by omohokcoj** [comment]
@schtack @AmbitionLover which database are you using?

**Comment by schtack** [comment]
i'm using postgresql database

**Comment by omohokcoj** [comment]
@schtack what is your docker run command? are you mounting docker container volumes on a network disk?

**Comment by schtack** [comment]
i think it was an error on my side , juste a typo ... anyways i'm getting this error now : 

2024-03-24 17:19:49 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

i did the update about one hour ago.

**Comment by omohokcoj** [comment]
@schtack does it work with the latest release - try to add FORCE_SSL=false to disable https redirect

**Comment by omohokcoj** [comment]
Closing, no response

**Comment by xavier-GitHub76** [comment]
Hello,

I have the same issue, caused by special character in postgres password.

POSTGRES_PASSWORD:"azerty%!" --> Error
POSTGRES_PASSWORD:"azerty!" --> OK

Best regards

**Comment by omohokcoj** [comment]
@xavier-GitHub76 @schtack do not use database URL but use the following variables:
DATABASE_HOST=
DATABASE_PORT=
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_NAME=

% is not a URL safe character and it breaks the URL
