### ISSUE TITLE
[BUG]  Stuck downloading when downloading an archived and completed document

### ISSUE THREAD

**Issue by jacobburrell** [docusealco/docuseal#275]
<img width="1228" alt="image" src="https://github.com/docusealco/docuseal/assets/61520543/1abc65b4-ad3a-4c2c-8347-af1dd575ad42">

<img width="383" alt="image" src="https://github.com/docusealco/docuseal/assets/61520543/8961698f-4c7b-4441-a8e6-b44ebce5af80">

When attempting to download an archived and completed document, the download process gets stuck and does not complete. 

Additionally, is there any way to unarchive a document from the web interface? Non-archived documents of different `Submissions` 
download just fine from the same document.

**Comment by sunshine69** [comment]
I saw the same issues here, completed doc can nto be downloaded. The error logs is like

```
E, [2024-05-22T22:01:05.428390 #1] ERROR -- : [49f6d004-f5c3-4020-896d-15148d0b18ea]   
[49f6d004-f5c3-4020-896d-15148d0b18ea] NoMethodError (undefined method `[]' for nil):
[49f6d004-f5c3-4020-896d-15148d0b18ea]   
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/submissions/generate_result_attachments.rb:312:in `build_pdf_attachment'
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/submissions/generate_result_attachments.rb:269:in `block in call'
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/submissions/generate_result_attachments.rb:266:in `map'
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/submissions/generate_result_attachments.rb:266:in `call'
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/submissions/ensure_result_generated.rb:27:in `call'
[49f6d004-f5c3-4020-896d-15148d0b18ea] app/controllers/submissions_download_controller.rb:22:in `index'
[49f6d004-f5c3-4020-896d-15148d0b18ea] lib/api_path_consider_json_middleware.rb:15:in `call'
```

**Comment by omohokcoj** [comment]
@sunshine69 could you please share the PDF that resulted in this error?

**Comment by omohokcoj** [comment]
Unable to reproduce
