### ISSUE TITLE
crash starting as non-root Docker container: SQLite3::ReadOnlyException: attempt to write a readonly database

### ISSUE THREAD

**Issue by meonkeys** [docusealco/docuseal#300]
I'm trying to get 1.6.2 running in Docker with sqlite in a non-root container. Is this supported?

* host OS: 64-bit Ubuntu 22.04.4 LTS desktop
* Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1
* image: `docuseal/docuseal:1.6.2`
* I have `docker-buildx` version `0.12.1-0ubuntu1~22.04.1` installed

Repro steps:

1. create a new group: `sudo groupadd e-sign` (got uid 1001)
2. create a new unprivileged user: `sudo useradd --shell /usr/sbin/nologin --no-create-home --gid e-sign e-sign` (got gid 1001)
3. start container: `docker run --rm -it --name docuseal -p 3000:3000 -u 1001:1001 -v e-sign:/data docuseal/docuseal`

I'm expecting it to create a default `docuseal.env` file and sqlite files in `/data/docuseal/`, but instead I'm seeing this:

<details><summary>(click to expand)</summary>

```
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.3.1-p55) ("The Eagle of Durango")
*  Min threads: 15
*  Max threads: 15
*  Environment: production
*          PID: 1
! Unable to load application: ActiveRecord::StatementInvalid: SQLite3::ReadOnlyException: attempt to write a readonly database
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
/usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `initialize': SQLite3::ReadOnlyException: attempt to write a readonly database (ActiveRecord::StatementInvalid)
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `new'
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `prepare'
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:221:in `execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:118:in `block (2 levels) in raw_execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:117:in `block in raw_execute'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:116:in `raw_execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:733:in `configure_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:693:in `block (2 levels) in reconnect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:376:in `reset_transaction'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:691:in `block in reconnect!'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:684:in `reconnect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:788:in `verify!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:795:in `connect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1001:in `block in with_raw_connection'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:33:in `block in internal_exec_query'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:32:in `internal_exec_query'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `query'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:100:in `query_value'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:418:in `get_database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:374:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:70:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:200:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:871:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:422:in `check_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:678:in `new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:723:in `checkout_new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:702:in `try_to_checkout_new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:654:in `acquire_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `checkout'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:182:in `connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:246:in `retrieve_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:287:in `retrieve_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:254:in `connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:510:in `migration_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
	from /app/config/initializers/migrate.rb:4:in `block in <main>'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `instance_exec'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `block in make_lambda'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `catch'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:203:in `block in halting'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `each'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `invoke_before'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/reloader.rb:96:in `prepare!'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/application.rb:426:in `initialize!'
	from /app/config/environment.rb:7:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:103:in `eval'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:103:in `new_from_string'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:94:in `load_file'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:64:in `parse_file'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:368:in `load_rackup'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:290:in `app'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/runner.rb:162:in `load_and_bind'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/single.rb:44:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/cli.rb:75:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:25:in `load'
	from /usr/local/bundle/bin/puma:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /app/bin/bundle:108:in `load'
	from /app/bin/bundle:108:in `<main>'
/usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `initialize': attempt to write a readonly database (SQLite3::ReadOnlyException)
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `new'
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:177:in `prepare'
	from /usr/local/bundle/gems/sqlite3-1.7.3/lib/sqlite3/database.rb:221:in `execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:118:in `block (2 levels) in raw_execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:117:in `block in raw_execute'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:116:in `raw_execute'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:733:in `configure_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:693:in `block (2 levels) in reconnect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:376:in `reset_transaction'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:691:in `block in reconnect!'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:684:in `reconnect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:788:in `verify!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:795:in `connect!'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1001:in `block in with_raw_connection'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:33:in `block in internal_exec_query'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3/database_statements.rb:32:in `internal_exec_query'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `query'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:100:in `query_value'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:418:in `get_database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:374:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:70:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/schema_cache.rb:200:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:871:in `database_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:422:in `check_version'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:678:in `new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:723:in `checkout_new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:702:in `try_to_checkout_new_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:654:in `acquire_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `checkout'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:182:in `connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:246:in `retrieve_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:287:in `retrieve_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/connection_handling.rb:254:in `connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:510:in `migration_connection'
	from /usr/local/bundle/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
	from /app/config/initializers/migrate.rb:4:in `block in <main>'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `instance_exec'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:448:in `block in make_lambda'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `catch'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:706:in `block in default_terminator'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:203:in `block in halting'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `each'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:598:in `invoke_before'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/callbacks.rb:109:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/reloader.rb:96:in `prepare!'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
	from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/application.rb:426:in `initialize!'
	from /app/config/environment.rb:7:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:103:in `eval'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:103:in `new_from_string'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:94:in `load_file'
	from /usr/local/bundle/gems/rack-3.0.11/lib/rack/builder.rb:64:in `parse_file'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:368:in `load_rackup'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/configuration.rb:290:in `app'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/runner.rb:162:in `load_and_bind'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/single.rb:44:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/lib/puma/cli.rb:75:in `run'
	from /usr/local/bundle/gems/puma-6.4.2/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:25:in `load'
	from /usr/local/bundle/bin/puma:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /app/bin/bundle:108:in `load'
	from /app/bin/bundle:108:in `<main>'
```

</details>

**Comment by omohokcoj** [comment]
@meonkeys does it work after you remove -u 1001:1001 ?

**Comment by meonkeys** [comment]
Yes.

**Comment by meonkeys** [comment]
What's the resolution? fixed / won't fix / not an issue / etc.?

**Comment by omohokcoj** [comment]
@meonkeys please reopen with more details  if you still have any issues deploying (i thought yes means that the issue has been fixed by removing the -u flag)

**Comment by meonkeys** [comment]
I'm still wondering if you intend for what I originally reported (running DocuSign as a non-root Docker container) to work, or if I'm doing something unsupported.

**Comment by omohokcoj** [comment]
@meonkeys the reported issue is not related to the docuseal app - it's related to linux/docker configurations and permissions
