### ISSUE TITLE
Cannot download new submissions after most recent update

### ISSUE THREAD

**Issue by thecircleisround** [docusealco/docuseal#323]
After most recent update any new submissions are failing to download. I just get the message "Failed to download files." From terminal I see ````NoMethodError (undefined method `value' for nil)```` when attempting to download before it raised sends 500 status code. This seems to also affect completed submissions from being emailed to the submitter.

**Comment by omohokcoj** [comment]
@thecircleisround could you share the entire log with error trace?
The issue might be related to the failed migration and your manual fix when adding ID : 1 account

**Comment by thecircleisround** [comment]
````
app-1        | E, [2024-07-25T18:38:15.206791 #1] ERROR -- : [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] undefined method `value' for nil
app-1        | I, [2024-07-25T18:38:15.210322 #1]  INFO -- : [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] {"method":"GET","path":"/submitters/4TGQnRYf2rjyoF/download","format":"*/*","controller":"SubmissionsDownloadController","action":"index","status":500,"allocations":38832,"duration":455.99,"view":0.0,"db":7.25,"fwd":"208.216.2.82"}
app-1        | E, [2024-07-25T18:38:15.212026 #1] ERROR -- : [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9]   
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] NoMethodError (undefined method `value' for nil):
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9]   
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] docuseal_ee (1.0) lib/submissions/generate_result_attachments.rb:162:in `info_creator'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/submissions/generate_result_attachments.rb:337:in `build_pdf_attachment'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/submissions/generate_result_attachments.rb:59:in `block in call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/submissions/generate_result_attachments.rb:56:in `map'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/submissions/generate_result_attachments.rb:56:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/submissions/ensure_result_generated.rb:27:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] app/controllers/submissions_download_controller.rb:22:in `index'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/abstract_controller/base.rb:224:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/rendering.rb:165:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/callbacks.rb:141:in `run_callbacks'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/abstract_controller/callbacks.rb:258:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/rescue.rb:25:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `block in instrument'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/notifications.rb:206:in `instrument'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activerecord (7.1.3.2) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/abstract_controller/base.rb:160:in `process'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionview (7.1.3.2) lib/action_view/rendering.rb:40:in `process'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal.rb:227:in `dispatch'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_controller/metal.rb:309:in `dispatch'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `each'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] warden (1.2.9) lib/warden/manager.rb:34:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/tempfile_reaper.rb:20:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/etag.rb:29:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/conditional_get.rb:31:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/head.rb:15:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `block in call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:39:in `tagged'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/tagged_logging.rb:135:in `tagged'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] activesupport (7.1.3.2) lib/active_support/broadcast_logger.rb:240:in `method_missing'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] railties (7.1.3.2) lib/rails/rack/logger.rb:24:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] request_store (1.6.0) lib/request_store/middleware.rb:19:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/method_override.rb:28:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/runtime.rb:24:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/static.rb:25:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] docuseal_ee (1.0) lib/favicons_middleware.rb:31:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/api_path_consider_json_middleware.rb:15:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] lib/normalize_client_ip_middleware.rb:14:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/deflater.rb:47:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] rack (3.0.11) lib/rack/sendfile.rb:114:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] actionpack (7.1.3.2) lib/action_dispatch/middleware/ssl.rb:79:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] railties (7.1.3.2) lib/rails/engine.rb:536:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
app-1        | [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
app-1        | I, [2024-07-25T18:38:15.215293 #1]  INFO -- : [bc776ebc-0f6a-4fa2-aff8-60f53a279bc9] {"method":"GET","path":"/500","format":"*/*","controller":"ErrorsController","action":"show","status":500,"allocations":298,"duration":0.86,"view":0.16,"db":0.0,"fwd":"208.216.2.82"}
````

**Comment by omohokcoj** [comment]
@thecircleisround seems like you're using Pro self-hosted app - Could you please email your Pro host to support@docuseal.co to help this resolved faster?
