### ISSUE TITLE
Unable to download completed submissions for a template.

### ISSUE THREAD

**Issue by araguma** [docusealco/docuseal#341]
When we try to download completed submissions for one of our templates we get the `Unable to download files` error alert. The error doesn't occur when the submission is partially signed, or for submissions in other templates.

```
E, [2024-08-15T18:34:21.542423 #1] ERROR -- : [a7008eb7-5e2d-4fa5-9982-b39527022308] undefined method `scan' for nil
I, [2024-08-15T18:34:21.544519 #1]  INFO -- : [a7008eb7-5e2d-4fa5-9982-b39527022308] {"method":"GET","path":"/submitters/Gk9WBYZomHc1XL/download","format":"*/*","controller":"SubmissionsDownloadController","action":"index","status":500,"allocations":110001,"duration":1816.75,"view":0.0,"db":4.55,"fwd":"192.168.50.1"}
E, [2024-08-15T18:34:21.545603 #1] ERROR -- : [a7008eb7-5e2d-4fa5-9982-b39527022308]
[a7008eb7-5e2d-4fa5-9982-b39527022308] NoMethodError (undefined method `scan' for nil):
[a7008eb7-5e2d-4fa5-9982-b39527022308]
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:203:in `block in generate_field_name'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/type/acro_form/form.rb:135:in `block (2 levels) in each_field'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/pdf_array.rb:183:in `block in each'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/pdf_array.rb:183:in `each_index'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/pdf_array.rb:183:in `each'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/type/acro_form/form.rb:129:in `each_with_index'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/type/acro_form/form.rb:129:in `block in each_field'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/type/acro_form/form.rb:143:in `each_field'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:203:in `each'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:203:in `map'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:203:in `generate_field_name'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:112:in `add'
[a7008eb7-5e2d-4fa5-9982-b39527022308] hexapdf (0.42.0) lib/hexapdf/document.rb:674:in `sign'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/submissions/generate_result_attachments.rb:447:in `build_pdf_attachment'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/submissions/generate_result_attachments.rb:61:in `block in call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/submissions/generate_result_attachments.rb:58:in `map'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/submissions/generate_result_attachments.rb:58:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/submissions/ensure_result_generated.rb:27:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] app/controllers/submissions_download_controller.rb:22:in `index'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/abstract_controller/base.rb:224:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/rendering.rb:165:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
[a7008eb7-5e2d-4fa5-9982-b39527022308] turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
[a7008eb7-5e2d-4fa5-9982-b39527022308] turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/callbacks.rb:141:in `run_callbacks'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/abstract_controller/callbacks.rb:258:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/rescue.rb:25:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/notifications.rb:206:in `block in instrument'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/notifications.rb:206:in `instrument'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activerecord (7.1.3.4) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/abstract_controller/base.rb:160:in `process'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionview (7.1.3.4) lib/action_view/rendering.rb:40:in `process'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal.rb:227:in `dispatch'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_controller/metal.rb:309:in `dispatch'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:51:in `block in serve'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `each'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `find_routes'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:882:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[a7008eb7-5e2d-4fa5-9982-b39527022308] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/tempfile_reaper.rb:20:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/etag.rb:29:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/conditional_get.rb:31:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/head.rb:15:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
[a7008eb7-5e2d-4fa5-9982-b39527022308] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `block in call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `block in tagged'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:39:in `tagged'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `tagged'
[a7008eb7-5e2d-4fa5-9982-b39527022308] activesupport (7.1.3.4) lib/active_support/broadcast_logger.rb:240:in `method_missing'
[a7008eb7-5e2d-4fa5-9982-b39527022308] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] request_store (1.6.0) lib/request_store/middleware.rb:19:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/request_id.rb:28:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/method_override.rb:28:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/runtime.rb:24:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] actionpack (7.1.3.4) lib/action_dispatch/middleware/static.rb:25:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/api_path_consider_json_middleware.rb:15:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] lib/normalize_client_ip_middleware.rb:14:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/deflater.rb:47:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] rack (3.1.7) lib/rack/sendfile.rb:114:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] railties (7.1.3.4) lib/rails/engine.rb:536:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
[a7008eb7-5e2d-4fa5-9982-b39527022308] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by omohokcoj** [comment]
@araguma can you please share your PDF that produces an error?

**Comment by araguma** [comment]
The PDF is this: [Registration 2024.pdf](https://github.com/user-attachments/files/16629026/Registration.2024.pdf)

**Comment by jeanGaston** [comment]
I'm encountering the same issue. On two different instances, none of the templates are downloadable once they are fully completed, though they are available when partially completed. I've tested this with three different PDFs and experienced the same problem.

**Comment by omohokcoj** [comment]
@jeanGaston can you please share your docker app error log?

**Comment by omohokcoj** [comment]
@jeanGaston the error log you shared doesn't contain errors

**Comment by jeanGaston** [comment]
My bad. After doing some research, here are the full logs. It seems like an issue with the signing algorithm. The certificate used for the signature is the one from Nginx Proxy Manager, which is just a basic Let's Encrypt certificate.

```
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.3.4-p94) ("The Eagle of Durango")
*  Min threads: 15
*  Max threads: 15
*  Environment: production
*          PID: 1
WARNING: Nokogiri was built against libxml version 2.12.9, but has dynamically loaded 2.12.7
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
2024-09-20T16:42:38.866Z pid=1 tid=t4x INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
2024-09-20T16:42:38.915Z pid=1 tid=t61 INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
2024-09-20T16:42:38.915Z pid=1 tid=t6l INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
2024-09-20T16:42:38.915Z pid=1 tid=t75 INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
2024-09-20T16:42:38.916Z pid=1 tid=t7p INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
2024-09-20T16:42:38.916Z pid=1 tid=t89 INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://default:REDACTED@0.0.0.0:6379/0"}
I, [2024-09-20T16:43:01.814781 #1]  INFO -- : [8b27b4a6-221b-4bc6-a42f-36aa07248a62] {"method":"GET","format":"html","controller":"SubmissionsController","action":"show","status":200,"allocations":109004,"duration":663.55,"view":258.08,"db":68.87,"fwd":"MY_IP","params":{"id":"3"},"host":"sign.domain.org","uid":1}
E, [2024-09-20T16:43:02.265940 #1] ERROR -- : [9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] Unsupported key type/signature algorithm
I, [2024-09-20T16:43:02.272099 #1]  INFO -- : [9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] {"method":"GET","format":"*/*","controller":"SubmissionsDownloadController","action":"index","status":500,"allocations":125002,"duration":538.45,"view":0.0,"db":64.2,"fwd":"MY_IP","params":{"slug":"uEA32"},"host":"sign.domain.org","uid":null}
E, [2024-09-20T16:43:02.273392 #1] ERROR -- : [9039c212-7ccf-4ca3-9f51-9c9fe5b3708a]
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] HexaPDF::Error (Unsupported key type/signature algorithm):
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a]
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signing/signed_data_creator.rb:189:in `create_signer_info'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signing/signed_data_creator.rb:113:in `create'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signing/signed_data_creator.rb:66:in `create'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signing/default_handler.rb:311:in `sign'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signing/default_handler.rb:273:in `signature_size'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/digital_signature/signatures.rb:130:in `add'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] hexapdf (0.42.0) lib/hexapdf/document.rb:674:in `sign'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/submissions/generate_result_attachments.rb:461:in `build_pdf_attachment'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/submissions/generate_result_attachments.rb:67:in `block in call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/submissions/generate_result_attachments.rb:58:in `map'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/submissions/generate_result_attachments.rb:58:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/submissions/ensure_result_generated.rb:27:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] app/controllers/submissions_download_controller.rb:22:in `index'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/abstract_controller/base.rb:224:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/rendering.rb:165:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] turbo-rails (2.0.5) lib/turbo-rails.rb:24:in `with_request_id'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] turbo-rails (2.0.5) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/callbacks.rb:141:in `run_callbacks'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/abstract_controller/callbacks.rb:258:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/rescue.rb:25:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/notifications.rb:206:in `block in instrument'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/notifications.rb:206:in `instrument'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activerecord (7.1.3.4) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/abstract_controller/base.rb:160:in `process'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionview (7.1.3.4) lib/action_view/rendering.rb:40:in `process'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal.rb:227:in `dispatch'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_controller/metal.rb:309:in `dispatch'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:51:in `block in serve'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `each'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:124:in `find_routes'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/routing/route_set.rb:882:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/tempfile_reaper.rb:20:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/etag.rb:29:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/conditional_get.rb:31:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/head.rb:15:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `block in call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `block in tagged'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:39:in `tagged'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `tagged'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] activesupport (7.1.3.4) lib/active_support/broadcast_logger.rb:240:in `method_missing'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] request_store (1.6.0) lib/request_store/middleware.rb:19:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/request_id.rb:28:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/method_override.rb:28:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/runtime.rb:24:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] actionpack (7.1.3.4) lib/action_dispatch/middleware/static.rb:25:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/api_path_consider_json_middleware.rb:15:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] lib/normalize_client_ip_middleware.rb:14:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/deflater.rb:47:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] rack (3.1.7) lib/rack/sendfile.rb:114:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] railties (7.1.3.4) lib/rails/engine.rb:536:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
[9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
I, [2024-09-20T16:43:02.275851 #1]  INFO -- : [9039c212-7ccf-4ca3-9f51-9c9fe5b3708a] {"method":"GET","format":"*/*","controller":"ErrorsController","action":"show","status":500,"allocations":321,"duration":1.19,"view":0.22,"db":0.0,"fwd":"MY_IP","params":{"slug":"uEA32"},"host":"sign.domain.org","uid":null}
I, [2024-09-20T16:43:39.374724 #1]  INFO -- : [d84be805-c4e1-46d4-905a-a2d398c0e6b8] {"method":"GET","format":"html","controller":"TemplatesController","action":"new","status":200,"allocations":4398,"duration":26.44,"view":17.01,"db":1.0,"fwd":"MY_IP","params":{},"host":"sign.domain.org","uid":1}
I, [2024-09-20T16:43:39.786854 #1]  INFO -- : [284cb065-7833-4faf-a5fd-082b33d1a955] {"method":"GET","format":"html","controller":"SubmissionsController","action":"show","status":200,"allocations":11797,"duration":56.35,"view":25.67,"db":8.56,"fwd":"MY_IP","params":{"id":"3"},"host":"sign.domain.org","uid":1}

**Comment by omohokcoj** [comment]
@jeanGaston your custom uploaded certificate is not suitable for document signing - removing the certificate and switching to the default certificate should solve the issue.
